name: Python Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-cov bandit pydantic objectpath lru-dict dotty-dict flatten-dict SQLAlchemy PyMySQL psycopg2cffi pymongo marshmallow marshmallow-oneofschema
      # - name: Analysing the code with pylint
      #   run: |
      #     pylint py_abac
      - name: Lint with ruff
        run: |
          ruff --format=github py_abac
      - name: Security check with bandit
        run: |
          bandit -r py_abac --skip B403,B301
      - name: Unit test with coverage
        run: |
          pytest --cov-config .coveragerc --cov=./ --cov-report html:htmlcov --cov-append
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: htmlcov

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017
